= mgr-simulation
:icons: font
Rafał Sławik <rafal.slawik@gmail.com>

Simulation project of some packet scheduling algorithms.

== Overview

Framework allows to simulate a scheduling algorithm against some adversary.
It is required to write down algorithm and adversary in special form.

== Installation

Requirements:

* https://www.python.org/[Python 3.4]
* http://matplotlib.org/[matplotlib]

=== Linux

. Install latest Python 3.
. Execute `pip install matplotlib`

=== OS X

. Install http://brew.sh/[Homebrew]
. Install Python 3 `brew install python3`
. Execute `pip3 install matplotlib`

=== Windows

. Install latest Python 3 from https://www.python.org/[www.python.org].
. Open Command Line and go to `C:\Python34\Scripts` (assuming default installation path).
. Execute `pip.exe install matplotlib`.
  This step may fail if Visual $$C++$$ 2010 (part of Visual Studio 2010) is not installed.
  Visual C++ is available http://www.dobreprogramy.pl/Visual-C,Program,Windows,12107.html[here].

== Algorithm

The main part of an algorithm is the `schedule` method that is called every time algorithm can make a scheduling decision.
Usually in reaction on an event.

[source,python]
----
class Algorithm:
    def schedule(self): # <1>
        pass
----
<1> Schedule packet method -- it returns scheduled packet length or `None` when algorithm is not going to sent anything.

NOTE: Handling packets queue is done internally.

== Adversary

Adversary consists of `schedule` and `scheduleError` methods.
Former one is used in adversary's algorithm (OFF or OPT).
Latter one is used to cause errors on the link.

[source,python]
----
class Adversary(Algorithm):
    def schedule(self): # <1>
        pass

    def scheduleError(self, packet): # <2>
        pass
----
<1> Schedule packet method -- it returns scheduled packet length or `None` when algorithm is not going to sent anything.
<2> Schedule error method -- return time in which next error occurs (in reaction on packet)

NOTE: Handling packets queue is done internally.

== Experiment

Each experiment constists of few part.
There is a file describing system.
Based on the file, a sequence on inject events is generated.
The sequence is used in simulation of both algorithms (algorithm under test and adversary's).
When algorithm under test makes a scheduling decision, adversary is asked to schedule an error.

=== Input

File describing system (model) contains parameters such as packet length, probability distribution.

.packets.in
----
3 5      // <1>
0.2      // <2>
0.2 0.8  // <3>
----
<1> Packet lengths.
<2> Parameter &#955;.
<3> Probability distribution.

NOTE: Lines 2 and 3 are optional.

=== generate.py

To generate sequence of inject events use:

 generate.py <generator> <n> <model>

==== Generator

* `sirocco_thm9` generator -- Generates inject event sequance using strategy described in Theorem 9.
* `stochastic` generator -- Generates inject events from exponential distribution with parameter &#955;.
   Packet length is randomly chosen with corresping probability (from distribution info file).

=== simulate.py

 simulate.py <algorithm> <adversary> <events file> <model>

Simulation produces a log, that containa records of moments when each algorithm have successfully transmitted a packet.

==== Algorithm

* `SL` -- Shortest Length
* `LL` -- Longest Length
* `SLPreamble`
* `CSLPreamble`
* `Greedy`
* `Prudent`
* `ESLPreamble`

==== Adversary

* `SiroccoThm9` -- Adversary from Theorem 9
* `SiroccoThm11` -- Adversary from Theorem 11
* `Sirocco` -- Adversary from section 4.1 in paper
* `ESirocco` -- Adversary from part 3.2.1 in thesis

=== plot.py

 plot.py <log>

Draw a simple graph of ratio: (sent by alg up to time t) / (sent by adv up to time t) over time t.

== Changelog
* Januray 2015
** Visualization in matplotlib
* 18.11-20.11.2014
** Experiment can be performed with single command
** Algorithm implementation makes use of Python generators
** Simplified experiment recording
* 11.11-13.11.2014
** Greedy algorithm implementation
* 02.11-04.11.2014
** Experiments
* 26.10.2014
** Experiments
* 25.10.2014
** Framework modifications
* 24.10.2014
** Adversarial input generation
* 21.10.2014
** Attempt to perform first expermient
* 20.10.2014
** Stochastic input generation
** Shortest and Longest Length Algorithm implementation
* 11.10.2014
** Plot drawing
** Stochastic input generation
* 09.10.2014
** Plot drawing
* 08.10.2014
** Simulation framework
** Algorithm, Adversary, Event, Events ported to python3
* 06.10.2014
** created repository
